[package]
name = "elizabeth"
version = "0.1.0"
license = "GPL-2.0"
authors = ["Daniel Serezane <serezane@protonmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
